//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturasiweb.Factura.Modelo
{
    using Facturasiweb.Factura.Modelo.Interfaces;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Clientes")]
    public partial class Cliente : Base, IUsuarioCreador
    {
        public string Descripcion { get; set; }
        public string Rfc { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }

        public int UsuarioId { get; set; }
        public int UsuarioCreadorId { get; set; }
        public int UsuarioModificadorId { get; set; }
        [ForeignKey("UsuarioId")]
        public virtual UsuarioSistema Usuario { get; set; }

        public virtual ICollection<Direccion> Direcciones { get; set; }
    }
}
