//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturasiweb.Factura.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("FactDetalles")]
    public partial class FactDetalle
    {
        [Key]
        [Column(Order = 1)]
        public int FacturaId { get; set; }
        [Key]
        [Column(Order = 2)]
        public string Codigo { get; set; }

        public int CatalogoId { get; set; }
        public int UnidadId { get; set; }
        public int ? SucursalId { get; set; }
        public string CuentaPredial { get; set; }
        public string Descripcion { get; set; }
        public string Lote { get; set; }
        public string FechaCaducidad { get; set; }
        public string CajaNotaVenta { get; set; }
        public string FolioNotaVenta { get; set; }
        public decimal Cantidad { get; set; }
        public decimal TasaIva { get; set; }
        public decimal TasaIeps { get; set; }
        public decimal TasaRetIva { get; set; }
        public decimal TasaRetIsr { get; set; }
        public decimal TasaDesc { get; set; }
        public decimal Precio { get; set; }
        public string TipoComplemento { get; set; }
        public string Complemento { get; set; }
        public int ? FolioInicial { get; set; }
        public int ? FolioFinal { get; set; }
        public virtual Facturasiweb.Factura.Modelo.Factura Factura { get; set; }
        [ForeignKey("CatalogoId")]
        public virtual CatSatProducto CatSatProducto { get; set; }
        [ForeignKey("UnidadId")]
        public virtual CatSatUnidad CatSatUnidad { get; set; }
    }
}
