//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Facturasiweb.Factura.TimbradoDLL.Utilerias {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Application", Namespace="http://facturacion.finkok.com/utilities")]
    public partial class UtilitiesSOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback report_totalOperationCompleted;
        
        private System.Threading.SendOrPostCallback report_uuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_xmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback datetimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_tokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback report_creditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UtilitiesSOAP() {
            this.Url = global::Facturasiweb.Factura.TimbradoDLL.Properties.Settings.Default.Facturasiweb_Factura_TimbradoDLL_Utilerias_UtilitiesSOAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event report_totalCompletedEventHandler report_totalCompleted;
        
        /// <remarks/>
        public event report_uuidCompletedEventHandler report_uuidCompleted;
        
        /// <remarks/>
        public event get_xmlCompletedEventHandler get_xmlCompleted;
        
        /// <remarks/>
        public event datetimeCompletedEventHandler datetimeCompleted;
        
        /// <remarks/>
        public event add_tokenCompletedEventHandler add_tokenCompleted;
        
        /// <remarks/>
        public event report_creditCompletedEventHandler report_creditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("report_total", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("report_totalResponse", Namespace="http://facturacion.finkok.com/utilities")]
        public report_totalResponse report_total([System.Xml.Serialization.XmlElementAttribute("report_total", Namespace="http://facturacion.finkok.com/utilities")] report_total report_total1) {
            object[] results = this.Invoke("report_total", new object[] {
                        report_total1});
            return ((report_totalResponse)(results[0]));
        }
        
        /// <remarks/>
        public void report_totalAsync(report_total report_total1) {
            this.report_totalAsync(report_total1, null);
        }
        
        /// <remarks/>
        public void report_totalAsync(report_total report_total1, object userState) {
            if ((this.report_totalOperationCompleted == null)) {
                this.report_totalOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreport_totalOperationCompleted);
            }
            this.InvokeAsync("report_total", new object[] {
                        report_total1}, this.report_totalOperationCompleted, userState);
        }
        
        private void Onreport_totalOperationCompleted(object arg) {
            if ((this.report_totalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.report_totalCompleted(this, new report_totalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("report_uuid", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("report_uuidResponse", Namespace="http://facturacion.finkok.com/utilities")]
        public report_uuidResponse report_uuid([System.Xml.Serialization.XmlElementAttribute("report_uuid", Namespace="http://facturacion.finkok.com/utilities")] report_uuid report_uuid1) {
            object[] results = this.Invoke("report_uuid", new object[] {
                        report_uuid1});
            return ((report_uuidResponse)(results[0]));
        }
        
        /// <remarks/>
        public void report_uuidAsync(report_uuid report_uuid1) {
            this.report_uuidAsync(report_uuid1, null);
        }
        
        /// <remarks/>
        public void report_uuidAsync(report_uuid report_uuid1, object userState) {
            if ((this.report_uuidOperationCompleted == null)) {
                this.report_uuidOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreport_uuidOperationCompleted);
            }
            this.InvokeAsync("report_uuid", new object[] {
                        report_uuid1}, this.report_uuidOperationCompleted, userState);
        }
        
        private void Onreport_uuidOperationCompleted(object arg) {
            if ((this.report_uuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.report_uuidCompleted(this, new report_uuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_xml", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("get_xmlResponse", Namespace="http://facturacion.finkok.com/utilities")]
        public get_xmlResponse get_xml([System.Xml.Serialization.XmlElementAttribute("get_xml", Namespace="http://facturacion.finkok.com/utilities")] get_xml get_xml1) {
            object[] results = this.Invoke("get_xml", new object[] {
                        get_xml1});
            return ((get_xmlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void get_xmlAsync(get_xml get_xml1) {
            this.get_xmlAsync(get_xml1, null);
        }
        
        /// <remarks/>
        public void get_xmlAsync(get_xml get_xml1, object userState) {
            if ((this.get_xmlOperationCompleted == null)) {
                this.get_xmlOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_xmlOperationCompleted);
            }
            this.InvokeAsync("get_xml", new object[] {
                        get_xml1}, this.get_xmlOperationCompleted, userState);
        }
        
        private void Onget_xmlOperationCompleted(object arg) {
            if ((this.get_xmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_xmlCompleted(this, new get_xmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("datetime", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("datetimeResponse", Namespace="http://facturacion.finkok.com/utilities")]
        public datetimeResponse datetime([System.Xml.Serialization.XmlElementAttribute("datetime", Namespace="http://facturacion.finkok.com/utilities")] datetime datetime1) {
            object[] results = this.Invoke("datetime", new object[] {
                        datetime1});
            return ((datetimeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void datetimeAsync(datetime datetime1) {
            this.datetimeAsync(datetime1, null);
        }
        
        /// <remarks/>
        public void datetimeAsync(datetime datetime1, object userState) {
            if ((this.datetimeOperationCompleted == null)) {
                this.datetimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndatetimeOperationCompleted);
            }
            this.InvokeAsync("datetime", new object[] {
                        datetime1}, this.datetimeOperationCompleted, userState);
        }
        
        private void OndatetimeOperationCompleted(object arg) {
            if ((this.datetimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.datetimeCompleted(this, new datetimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("add_token", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("add_tokenResponse", Namespace="http://facturacion.finkok.com/utilities")]
        public add_tokenResponse add_token([System.Xml.Serialization.XmlElementAttribute("add_token", Namespace="http://facturacion.finkok.com/utilities")] add_token add_token1) {
            object[] results = this.Invoke("add_token", new object[] {
                        add_token1});
            return ((add_tokenResponse)(results[0]));
        }
        
        /// <remarks/>
        public void add_tokenAsync(add_token add_token1) {
            this.add_tokenAsync(add_token1, null);
        }
        
        /// <remarks/>
        public void add_tokenAsync(add_token add_token1, object userState) {
            if ((this.add_tokenOperationCompleted == null)) {
                this.add_tokenOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_tokenOperationCompleted);
            }
            this.InvokeAsync("add_token", new object[] {
                        add_token1}, this.add_tokenOperationCompleted, userState);
        }
        
        private void Onadd_tokenOperationCompleted(object arg) {
            if ((this.add_tokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_tokenCompleted(this, new add_tokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("report_credit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("report_creditResponse", Namespace="http://facturacion.finkok.com/utilities")]
        public report_creditResponse report_credit([System.Xml.Serialization.XmlElementAttribute("report_credit", Namespace="http://facturacion.finkok.com/utilities")] report_credit report_credit1) {
            object[] results = this.Invoke("report_credit", new object[] {
                        report_credit1});
            return ((report_creditResponse)(results[0]));
        }
        
        /// <remarks/>
        public void report_creditAsync(report_credit report_credit1) {
            this.report_creditAsync(report_credit1, null);
        }
        
        /// <remarks/>
        public void report_creditAsync(report_credit report_credit1, object userState) {
            if ((this.report_creditOperationCompleted == null)) {
                this.report_creditOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreport_creditOperationCompleted);
            }
            this.InvokeAsync("report_credit", new object[] {
                        report_credit1}, this.report_creditOperationCompleted, userState);
        }
        
        private void Onreport_creditOperationCompleted(object arg) {
            if ((this.report_creditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.report_creditCompleted(this, new report_creditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class report_total {
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private System.DateTime date_fromField;
        
        private System.DateTime date_toField;
        
        private string invoice_typeField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date_from {
            get {
                return this.date_fromField;
            }
            set {
                this.date_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date_to {
            get {
                return this.date_toField;
            }
            set {
                this.date_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string invoice_type {
            get {
                return this.invoice_typeField;
            }
            set {
                this.invoice_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ReportTotalCredit {
        
        private string taxpayer_idField;
        
        private string creditField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ReportTotalCreditResult {
        
        private ReportTotalCredit[] resultField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ReportTotalCredit[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class report_creditResponse {
        
        private ReportTotalCreditResult report_creditResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReportTotalCreditResult report_creditResult {
            get {
                return this.report_creditResultField;
            }
            set {
                this.report_creditResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class report_credit {
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ResponseToken {
        
        private string usernameField;
        
        private System.Nullable<bool> statusField;
        
        private bool statusFieldSpecified;
        
        private string nameField;
        
        private System.Nullable<bool> successField;
        
        private bool successFieldSpecified;
        
        private string tokenField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class add_tokenResponse {
        
        private ResponseToken add_tokenResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseToken add_tokenResult {
            get {
                return this.add_tokenResultField;
            }
            set {
                this.add_tokenResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class add_token {
        
        private string usernameField;
        
        private string passwordField;
        
        private string nameField;
        
        private string token_usernameField;
        
        private string taxpayer_idField;
        
        private System.Nullable<bool> statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string token_username {
            get {
                return this.token_usernameField;
            }
            set {
                this.token_usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class DateResult {
        
        private string errorField;
        
        private string datetimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class datetimeResponse {
        
        private DateResult datetimeResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateResult datetimeResult {
            get {
                return this.datetimeResultField;
            }
            set {
                this.datetimeResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class datetime {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class XMLResult {
        
        private string xmlField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class get_xmlResponse {
        
        private XMLResult get_xmlResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public XMLResult get_xmlResult {
            get {
                return this.get_xmlResultField;
            }
            set {
                this.get_xmlResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class get_xml {
        
        private string usernameField;
        
        private string passwordField;
        
        private string uuidField;
        
        private string taxpayer_idField;
        
        private string invoice_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string invoice_type {
            get {
                return this.invoice_typeField;
            }
            set {
                this.invoice_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ReportUUID {
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ReportUUIDResult {
        
        private ReportUUID[] invoicesField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ReportUUID[] invoices {
            get {
                return this.invoicesField;
            }
            set {
                this.invoicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class report_uuidResponse {
        
        private ReportUUIDResult report_uuidResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReportUUIDResult report_uuidResult {
            get {
                return this.report_uuidResultField;
            }
            set {
                this.report_uuidResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class report_uuid {
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private System.DateTime date_fromField;
        
        private System.DateTime date_toField;
        
        private string invoice_typeField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date_from {
            get {
                return this.date_fromField;
            }
            set {
                this.date_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date_to {
            get {
                return this.date_toField;
            }
            set {
                this.date_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string invoice_type {
            get {
                return this.invoice_typeField;
            }
            set {
                this.invoice_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ReportTotal {
        
        private string totalField;
        
        private string taxpayer_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ReportTotalResult {
        
        private ReportTotal[] resultField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ReportTotal[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/utilities")]
    public partial class report_totalResponse {
        
        private ReportTotalResult report_totalResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReportTotalResult report_totalResult {
            get {
                return this.report_totalResultField;
            }
            set {
                this.report_totalResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void report_totalCompletedEventHandler(object sender, report_totalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class report_totalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal report_totalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public report_totalResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((report_totalResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void report_uuidCompletedEventHandler(object sender, report_uuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class report_uuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal report_uuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public report_uuidResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((report_uuidResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_xmlCompletedEventHandler(object sender, get_xmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_xmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_xmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public get_xmlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((get_xmlResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void datetimeCompletedEventHandler(object sender, datetimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class datetimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal datetimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public datetimeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((datetimeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void add_tokenCompletedEventHandler(object sender, add_tokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_tokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_tokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public add_tokenResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((add_tokenResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void report_creditCompletedEventHandler(object sender, report_creditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class report_creditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal report_creditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public report_creditResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((report_creditResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591